--handle = io.popen('cd')
--executePath = handle\read()
--package.path = executePath .. '\\?.lua;' .. executePath .. '\\?\\init.lua;' .. package.path
--
--secua = (require 'secua')('secua')
--
--input = secua.utils.hexBytify '76696f6c61'
--result = secua.utils.hexify (secua.sha3.keccakSHA input, 512)
--print result
